version: "3"
services:
  api:
    image: movies-api-api
    container_name: flask-api
    restart: always
    ports:
      - "5001:5001"
    environment:
      API_KEY: onVF1xD53e3zL4x68NIJIYytCe4
      BASE_DATABASE_URL: mysql+pymysql://naru:546326@192.168.74.207:3312/movies
    networks:
      - app-network
networks:
  app-network:
    driver: bridge


